version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:15.0-alpine3.16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: tinyurlpassword
      POSTGRES_USER: tinyurluser
      POSTGRES_DB: tinyurl
  redis:
    image: redis:7.0.5-alpine3.16
    container_name: redis
  tinyurl:
    container_name: tinyurl
    environment:
      DJANGO_HOST: http://localhost:8000
      DJANGO_DB_TYPE: postgres
      DJANGO_DB_USER: tinyurluser
      DJANGO_DB_NAME: tinyurl
      DJANGO_DB_PASSWORD: tinyurlpassword
      DJANGO_DB_HOST: postgres
      DJANGO_DB_PORT: 5432
      DJANGO_CACHE_TYPE: redis
      DJANGO_REDIS_HOST: redis://redis:6379
      DJANGO_REDIS_DB: 1
      DJANGO_DEBUG: FALSE
    depends_on:
      - postgres
      - redis
    build:
      context: simpletinyurl
      dockerfile: Dockerfile
    ports:
      - "8000:8000"