# Generated by Django 4.1.2 on 2022-10-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('alias', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('long_url', models.URLField()),
            ],
        ),
    ]
